### ISSUE TITLE
'dict object' has no attribute 'executor'

### ISSUE THREAD

**Issue by justfortherec** [riemers/ansible-gitlab-runner#133]
After updating `gitlab-runner` from version 1.2.3 to 1.6.17 I see the following error:
```
FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'executor'\n\nThe error appears to have been in '/home/fxg/.ansible/roles/riemers.gitlab-runner/tasks/update-config-runner.yml': line 82, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set runner executor section\n  ^ here\n"}
```

Explicitly adding the default option `shell` has resolved the problem.

```diff
 gitlab_runner_runners:
   - name: '{{ runner_name }}'
     tags:
       - python3
       - host-iron
+    executor: shell
```

Has this been changed to a mandatory value? From what I see in the failed task, it seems that it should default to `shell` anyway.

**Comment by riemers** [comment]
If it should default to shell according to the task then could you check why it does not, time is limited for me at the moment.
